---
- name: apt dist-upgrade
  apt:
    upgrade: dist
    update_cache: yes

- name: Install basic software
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - etckeeper
    - dnsutils
    - git
    - htop
    - ntp
    - tmux
    - ufw
    - vim

- name: apt autoclean
  apt:
    autoclean: yes

- name: apt autoremove
  apt:
    autoremove: yes
