---
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"
  tags: hostname

- name: Set color prompt
  lineinfile:
    path: /root/.bashrc
    line: "force_color_prompt=yes\nPS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '"

- name: Install packages
  import_tasks: apt.yml
  tags: apt

- name: Firewall settings
  import_tasks: ufw.yml
  tags: ufw

- name: SSHD settings
  import_tasks: sshd.yml
  tags: sshd
