---
- name: Allow SSH root login
  replace:
    path: /etc/ssh/sshd_config
    regexp: "^#? ?PermitRootLogin no"
    replace: "PermitRootLogin yes"
  notify: restart sshd
 
- name: Disable SSH password login
  replace:
    path: /etc/ssh/sshd_config
    regexp: "^#? ?PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  notify: restart sshd

- name: Disable X11 forwarding
  replace:
    path: /etc/ssh/sshd_config
    regexp: "^#? ?X11Forwarding yes"
    replace: "X11Forwarding no"
  notify: restart sshd
